apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: asif
  region: us-east-1

managedNodeGroups:
- name: spot
  instanceTypes: ["t3.medium","t3.large","c5a.large"]
  spot: true
  desiredCapacity: 2